### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by hankolsen**

### CODE REVIEW

**Review by ludvigbartholdsson — COMMENTED** [review]
Can you clarify exactly what else I should do to finalize the ci/cd with publish to the stores? (chrome + firefox)

**Comment by hankolsen** [comment]
> Can you clarify exactly what else I should do to finalize the ci/cd with publish to the stores? (chrome + firefox)

Follow the steps here: https://docs.plasmo.com/framework/workflows/submit

**Comment by ludvigbartholdsson** [comment]
> > Can you clarify exactly what else I should do to finalize the ci/cd with publish to the stores? (chrome + firefox)
> 
> Follow the steps here: https://docs.plasmo.com/framework/workflows/submit

What about FireFox? Can't see that you mention it in the `submit.yml`.

**Comment by hankolsen** [comment]
Maybe here?

https://docs.plasmo.com/itero/publisher
https://docs.plasmo.com/itero/publisher#firefox-add-ons-store

**Pull request merged**
